# Syntax highlighting for Dockerfile.

syntax dockerfile "Dockerfile$"

comment "# "

# Keywords.
color blue "^[A-Z]{3,} "

# Environment variables.
icolor yellow "\$[0-9a-z_]+"
icolor yellow "\$\{[0-9a-z_]+(:[+-][0-9a-z_]*)?\}"

# Strings.
color green ""([^"\]|\\.)*""

# Comments.
color red "^ *#.*"

# Trailing whitespaces.
color ,green " +$"
