# Syntax highlighting for Dockerfile.

syntax dockerfile "Dockerfile$"

comment "# "

# Keywords.
color blue "^[[:upper:]]+[[:blank:]]"

# Environment variables.
color magenta "\$[[:alnum:]_]+"
color magenta "\$\{[[:alnum:]_]+(:[+-][[:alnum:]_]*)?\}"

# Strings.
color green ""([^"]|\\")*""

# Comments.
color red "(^|[[:blank:]])#.*"

# Trailing whitespace.
color ,green "[[:space:]]+$"
